### PR TITLE
Fix unknown app ops code from xiaomi devices.

### PR DESCRIPTION
**Pull request by d4rkk3y**
xiaomi_ops
xiaomi_ops2

We can get the custom app ops code and its name by reverse engineering Permission Manager app from stock rom of any xiaomi devices or can get one here:
https://www.apkmirror.com/apk/xiaomi-inc/permission-manager/permission-manager-1-2-8-release/

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
Nice work!

Please fix the formatting. You can do that on Android Studio by pressing <tt>ctrl</tt> + <tt>alt</tt> + <tt>L</tt>.

**Comment by MuntashirAkon** [comment]
Thanks. It looks better now.

**Comment by MuntashirAkon** [comment]
@d4rkk3y Since it's related, do you know what mode 5 does on MIUI? AOSP has up to mode 4 but MIUI seems to have a few extra modes.

**Comment by d4rkk3y** [comment]
> @d4rkk3y Since it's related, do you know what mode 5 does on MIUI? AOSP has up to mode 4 but MIUI seems to have a few extra modes.

I have extracted the framework.jar from lasted MIUI 12. And discovered that MIUI actually have 5 mode. It is MODE_ALLOWED=0, MODE_IGNORED=1, MODE_ERRORED=2, MODE_DEFAULT=3, MODE_FOREGOUND=4 and a extra mode call: MODE_ASK=5. Moreover, miui custom op start from 10000 and end at 10033(at the lasted miui 12).
miui_ops

**Comment by MuntashirAkon** [comment]
Hmm. They haven't added it to the `MODE_NAMES` array, I see.

**Comment by d4rkk3y** [comment]
Btw, in the last commit, there are some app ops are missed. I have just discovered it when check the lastest miui 12 framework.jar. And I fix mode=5 =>ask also. Should I create another pull request?

**Comment by MuntashirAkon** [comment]
> Should I create another pull request?

Yeah.

**Pull request merged**
