### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
Thank you for the app! I've made a few improvements to this file to help out a little.

Nothing controversial except moved the dark screenshots above the light ones because most of us tech-savvy people are using dark themes these days.

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
Merged via a9be2d5a.

**Comment by Gitoffthelawn** [comment]
On my end, it shows "Merged with a9be2d5", and then "Closed with unmerged commits".  Why is it showing that?

**Comment by MuntashirAkon** [comment]
> Why is it showing that?

It was merged using the [patch](https://github.com/MuntashirAkon/AppManager/pull/192.patch). Apparently, they cannot display _merged_ unless **GitHub** is the committer.

**Comment by Gitoffthelawn** [comment]
Interesting! Thank you for the explanation.

**Pull request closed without merging**
