### PR TITLE
Add Albanian language

### PR DESCRIPTION
**Pull request by cocka11**
Coming soon translante all strings.

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
Thanks for your contribution but this PR cannot be merged right now, because

- You haven't followed the [contributing guidelines](https://github.com/MuntashirAkon/AppManager/blob/master/CONTRIBUTING.rst).
- You have translated untranslatable strings i.e. strings with `translatable` property set to `false`.

How to solve the issues:
- Go through the contributing page linked above.
- Remove all untranslatable strings.
- Create a new PR with the said changes.

**Comment by MuntashirAkon** [comment]
Also, after the PR has been merged, you must translate App Manager though [Weblate](https://hosted.weblate.org/projects/app-manager/).

**Comment by cocka11** [comment]
Albanian language not is in list to website

Të dielën, më 31 tetor 2021, Muntashir Al-Islam ***@***.***>
shkroi:

**Comment by MuntashirAkon** [comment]
> Albanian language not is in list to website

There's an option to request a new language. Anyway, I've added Albanian there as well.

**Comment by cocka11** [comment]
Thanks bro

Të hënën, më 1 nëntor 2021, Muntashir Al-Islam ***@***.***>
shkroi:

**Pull request closed without merging**
