### PR TITLE
Use pandoc instead of make4ht

### PR DESCRIPTION
**Pull request by gnuhead-chieb**
https://github.com/MuntashirAkon/AppManager/pull/418

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
Merged via a39d33be

**Comment by MuntashirAkon** [comment]
Is it possible to have a more control over the `amalert`? It would be better if it was possible to access them (tip, warning, danger) via CSS separately (say with `.tip`, `.warning` and `.danger` classes).

**Comment by gnuhead-chieb** [comment]
> Is it possible to have a more control over the `amalert`? It would be better if it was possible to access them (tip, warning, danger) via CSS separately (say with `.tip`, `.warning` and `.danger` classes).

Before convert with script,it is like this
`<div class="amalert--COLORCODE">`
Script will convert this to
`<div class="amalert" style="border: 3.0pt solid #COLORCODE;">`

in this convertion part of script
https://github.com/MuntashirAkon/AppManager/blob/a39d33be9e12354fbd61fa895c05b4d2a43c17d4/docs/raw/latex/doctool.sh#L54

So,to make separately,simply change sed code on this part to can use separate class name.
you also may want to change
https://github.com/MuntashirAkon/AppManager/blob/a39d33be9e12354fbd61fa895c05b4d2a43c17d4/docs/raw/latex/main.tex#L54

**Comment by gnuhead-chieb** [comment]
Also, You have to change some variable to args("$1-$x").It is currently certain for debug.
https://github.com/MuntashirAkon/AppManager/blob/a39d33be9e12354fbd61fa895c05b4d2a43c17d4/docs/raw/latex/doctool.sh#L99

**Comment by gnuhead-chieb** [comment]
It is off-topic comment but i write here so you seem disable watching on that repo
Did you stop managing Metro repo?If it so,it should write as it discontinued.

**Comment by MuntashirAkon** [comment]
> Did you stop managing Metro repo?

Yes, but I have promised one last build based on the latest version of Retro.

**Comment by MuntashirAkon** [comment]
The hack to add hyperlinks in the section title is broken in pandoc 2.17. Have you asked them to add such as a feature? It isn't much difficult, I think.

**Comment by gnuhead-chieb** [comment]
v2.13 is recommended now.if you get something broken after update pandoc, it need changing script.

**Comment by MuntashirAkon** [comment]
Replaced with Lua script. 309d1ebc

**Comment by gnuhead-chieb** [comment]
https://github.com/MuntashirAkon/AppManager/blob/309d1ebc45137d06e8b99bde0a0a40602edc5769/docs/raw/latex/doctool.sh#L26

-z is better, and should set output to index.html if input is none
Example:
https://github.com/gnuhead-chieb/solibs/blob/ad2cac129fb67d7f42efe266ea5ac04021fd1add/checker.sh#L9-L10


https://github.com/MuntashirAkon/AppManager/blob/309d1ebc45137d06e8b99bde0a0a40602edc5769/docs/raw/latex/doctool.sh#L67-L68

https://github.com/MuntashirAkon/AppManager/blob/309d1ebc45137d06e8b99bde0a0a40602edc5769/docs/raw/latex/doctool.sh#L115-L116

should enclose variable with "",for avoid unexpected bug

**Comment by MuntashirAkon** [comment]
Do not worry about them. The bash script has to be replaced. It has too many dependencies.

> should set output to index.html if input is none

All fields have been made mandatory to avoid accidental modifications.

**Comment by gnuhead-chieb** [comment]
> It has too many dependencies.

sed,awk,grep can be replaced by perl.

**Comment by gnuhead-chieb** [comment]
> How does update works? Suppose I have altered the docs and want to update the `strings-ja.xml` with pre-existing translations, what does this the command `./doctool.sh update strings-ja.xml` do?

update should use for base text,weblate can update localized strings from base strings

**Comment by MuntashirAkon** [comment]
> sed,awk,grep can be replaced by perl.

Perl makes things even more slow. I'll use a PHP 7+ script instead. PHP is the fastest scripting language without any external dependencies. Memory consumption will be a bit higher though, but that's not an issue.

**Comment by gnuhead-chieb** [comment]
> Perl makes things even more slow. I'll use a PHP 7+ script instead. PHP is the fastest scripting language without any external dependencies. Memory consumption will be a bit higher though, but that's not an issue.

It uess many advanced regexs.Rewriting those by other language may too complicated

**Comment by MuntashirAkon** [comment]
> It uess many advanced regexs.Rewriting those by other language may too complicated

PHP7.3+ uses PCRE2-JIT by default. It is the fastest engine and supports more advanced syntax than any other regex engines. `sed` and `perl` is nothing compared to that in both syntax and performance.

There is also an issue with the script. It searches and adds all the `.tex` files which it shouldn't do. It should find all the `\input` commands recursively from the `main.tex` and adds them only. Anyway, I will take care of the issues.

Anyway, Weblate is unable to parse the strings.xml. I have received the following E-Mail:

```
#  Parse error

[Hosted Weblate](https://hosted.weblate.org/) / [App
Manager](https://hosted.weblate.org/projects/app-manager/) /
[Docs](https://hosted.weblate.org/projects/app-manager/docs/) /
[English](https://hosted.weblate.org/projects/app-manager/docs/en/)

## Error message

    
    
    bad unicode escape sequence
    

## Failing file

docs/raw/en/strings.xml

##  Translation Info

All strings                                                                |  [ 833 ](https://hosted.weblate.org/translate/app- 
manager/docs/en/)                                                          |                                                    
---------------------------------------------------------------------------|----------------------------------------------------|----
Translated strings                                                         |  [ 833 ](https://hosted.weblate.org/translate/app- 
manager/docs/en/?q=state:>=translated)                                     |  [ 100%                                            
](https://hosted.weblate.org/translate/app-                                
manager/docs/en/?q=state:>=translated)                                     
Untranslated strings                                                       |  [ 0 ](https://hosted.weblate.org/translate/app-   
manager/docs/en/?q=state:empty)                                            |  [ 0%                                              
](https://hosted.weblate.org/translate/app-manager/docs/en/?q=state:empty) 
Unfinished strings                                                         |  [ 0 ](https://hosted.weblate.org/translate/app-   
manager/docs/en/?q=state:<translated)                                      |  [ 0%                                              
](https://hosted.weblate.org/translate/app-                                
manager/docs/en/?q=state:<translated)                                      
Strings marked for edit                                                    |  [ 0 ](https://hosted.weblate.org/translate/app-   
manager/docs/en/?q=state:needs-editing)                                    |  [ 0%                                              
](https://hosted.weblate.org/translate/app-manager/docs/en/?q=state:needs- 
editing)                                                                   


[View](https://hosted.weblate.org/projects/app-manager/docs/en/)

  
[Weblate, the libre continuous localization system.](https://weblate.org/)

▸ [Notification
settings](https://hosted.weblate.org/accounts/profile/#notifications)

Generated on Feb. 11, 2022, 5:49 p.m..
```

**Comment by gnuhead-chieb** [comment]
It seems bug of weblate's translate-toolkit
https://github.com/translate/translate/issues/4320

**Comment by MuntashirAkon** [comment]
So, all these efforts amount nothing because of a bug in Weblate (again)?

**Comment by gnuhead-chieb** [comment]
It need to stop using xliff and change it to others(eg, po, json)

**Comment by gnuhead-chieb** [comment]
It seems need to escape \n

**Comment by gnuhead-chieb** [comment]
Apply this patch and try again
[fix.txt](https://github.com/MuntashirAkon/AppManager/files/8051093/fix.txt)

**Comment by MuntashirAkon** [comment]
Yes, I am trying to reuse the existing PHP functions to see if it works.

**Comment by MuntashirAkon** [comment]
Hmm, I think the biggest issue while merging is finding which string belong to which file. We can reduce the overhead by specifying file name in the strings without the file extension. E.g.

Section title of `pages/main-page.tex` would become `pages_main-page_section==title` where `_` are used in place of `/` and `.` and we could use the `-` to separate words as usual. We're already using something similar so we can use this specific format instead.

**Comment by MuntashirAkon** [comment]
Hmm, [working now](https://hosted.weblate.org/projects/app-manager/docs/). I've followed [Android developer's guide](https://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling) + escaping the slash (I already do this in other places though).

However, I still need to decide about the naming convention. Since underscore has special meaning and IDEs handle them specially, I thing `$` would be a better choice. We can modify the rule above as follows:

For directory separator, `/` and `.tex`, we will use `$` (will be assigned automatically), and for titles we will use `$` prefix.

Examples: (assume the tex file is `pages/main-page.tex`)
1. Title
```latex
\section{Main Page}\label{sec:main-page} %%!!$head>>
```
```xml
<string name="pages$main-page$$head">Main Page</string>
```
2. Body
```latex
%%!!intro<<
Main page lists all the installed, uninstalled and backed up applications. A single click on any installed app item
opens the respective \hyperref[sec:app-details-page]{App Details page}. For the uninstalled system apps, it displays a
dialog prompt which can be used to reinstall the app. Using the \hyperlink{par:main-page-sort}{sort} option from the
list options, the app items can be sorted in various ways and preserved on exit. It is also possible to filter items
using the \hyperlink{par:main-page-filter}{filter} option in the list options. Filtering is possible also via the search
bar with additional support for the regular expressions.
%%!!>>
```
```xml
<string name="pages$main-page$intro">Main page lists all the installed, uninstalled and backed up applications. A single click on any installed app item
opens the respective \\hyperref[sec:app-details-page]{App Details page}. For the uninstalled system apps, it displays a
dialog prompt which can be used to reinstall the app. Using the \\hyperlink{par:main-page-sort}{sort} option from the
list options, the app items can be sorted in various ways and preserved on exit. It is also possible to filter items
using the \\hyperlink{par:main-page-filter}{filter} option in the list options. Filtering is possible also via the search
bar with additional support for the regular expressions.</string>
```

This makes things more simple, don't you think?

**Comment by gnuhead-chieb** [comment]
yeah.

**Comment by gnuhead-chieb** [comment]
it seems line break couldn't handled by weblate

**Comment by MuntashirAkon** [comment]
> it seems line break couldn't handled by weblate

Yes, I have to replace them with `\n`.

**Comment by MuntashirAkon** [comment]
Should be fixed now.

**Comment by MuntashirAkon** [comment]
I think it's ready to be launched. I will add a few languages for testing purposes first.

**Comment by MuntashirAkon** [comment]
Just thinking: Our localisation effort should be shared to others so that they might not have to go through all the trouble we had to do endure. I'm still curious as to why there isn't any sane way to localise documentation though.

**Comment by MuntashirAkon** [comment]
Regex error on their side, it must be that `\\b` has been translated as `\b` and finally to nothing due to regex error.

**Comment by MuntashirAkon** [comment]
Why regex though? A simple dom manipulation was enough.

**Comment by gnuhead-chieb** [comment]
Screenshot_20220213_162853
It seems it only happens in titlepage.
Other page works correctly

**Comment by gnuhead-chieb** [comment]
Try remove indent

**Comment by MuntashirAkon** [comment]
Fixed. However, this should be reported to Weblate though.

**Comment by gnuhead-chieb** [comment]
i'll translate it after [colobot](https://github.com/colobot/colobot) is done.i"m translating this

**Comment by gnuhead-chieb** [comment]
https://muntashirakon.github.io/AppManager/en/#subsubsec:details:servcies
foreground service-->background service
optimisation-->optimization

https://muntashirakon.github.io/AppManager/en/#toc:subsec:main-colour-codes
Color name wrong

**Comment by MuntashirAkon** [comment]
> foreground service-->background service

It's a technical term. See https://developer.android.com/guide/components/foreground-services

> optimisation-->optimization
> Color name wrong

British English

**Comment by gnuhead-chieb** [comment]
#4f1c14 is dark red in https://muntashirakon.github.io/AppManager/en/#subsec:main-colour-codes but very dark red in https://muntashirakon.github.io/AppManager/en/#subsec:app-details-colour-codes

**Comment by gnuhead-chieb** [comment]
Typo

https://muntashirakon.github.io/AppManager/en/#toc:subsec:signatures-tab
singing certificates→signing certificates

**Comment by MuntashirAkon** [comment]
After much testing, it was concluded that the method proposed by you was very stable. However, in order to speed up the process, I have converted the script into PHP (7.1 and later) along with many improvements, and acde06dc2610ef31213a28e6c1c950a30035de74 finalises process (minus integrating the abuse checker, for now). Thanks for all your helps 👍

**Comment by gnuhead-chieb** [comment]
Regex finding broken TeX tags
```
(?<!\\\\)(textbf|textit)
(textbf|textit)(?!{.*?})
```

**Comment by gnuhead-chieb** [comment]
It should separate strings when its text is too long by adding suffix such as _1, _2.
If text is too long,it makes inconvenient on managing translation.

https://user-images.githubusercontent.com/41156994/166111876-b51f0132-4501-4ad3-850b-f2d0afa23568.mp4

**Comment by MuntashirAkon** [comment]
Hmm, I shall keep that in mind in the future.

**Pull request closed without merging**
