### PR TITLE
Add more debloat profiles

### PR DESCRIPTION
**Pull request by gnuhead-chieb**
Pulled from my UAD fork
https://gitlab.com/gnuhead-chieb/universal-android-debloater/-/tree/gnuhead-chieb-master-patch-69000

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
Have you tested them to ensure that nothing gets broken?

**Comment by gnuhead-chieb** [comment]
These lists are taken from many websites and I merged them.
And I haven't checked myself because I don't have bloated device.

Here is example of source of debloat list
https://github.com/whilstanp/master/blob/master/adb%20uninstall.txt
https://github.com/Bagus18/Bagus18.github.io/blob/25d87202d8d22004e3ade75d6a9c904d0642f14a/_posts/2018-10-16-uninstall-system-app.markdown
https://mobile9.jp.net/adb-app-block/
https://github.com/conochy/Android-PreinstallApp-Disable/tree/SH-02M
https://github.com/LufsX/Sony-XC-per-installed/blob/master/Useless_Per-installed_APP.txt
https://github.com/Npepperlinux/SettingXperiaZ4Tablet/blob/main/docomo.sh
https://nanigashitainda.hatenablog.com/entry/20201116/1605535478
https://github.com/saga0324/nippon_keitai_rubbish_sw_list/tree/master
https://github.com/Jay-2512/Sony-Xperia-X-Compact-Japanese-Debloater/blob/main/Linux/xperia_xc_debloater.sh
https://github.com/toranoko0518/kill-dcm/blob/master/kill-dcm.sh
https://github.com/GitCat99/jp.adb.tool
https://github.com/nukadelic/CheatSheet/blob/master/Android/ADB.SamsungS8.md
https://github.com/syagawa/android-rm-pkg/blob/master/_pkgs
https://github.com/SimplyRin/ichika/blob/main/SO-04J.bat
https://github.com/Kn0ws/HTV32BloatwareRemover/blob/master/HTV32BloatwareRemover.bat
https://github.com/KushagraKarira/Debloat
https://www.reddit.com/r/lgg8/comments/ium6hs/g8_korean_variant_dual_clock_and_sms_fix/
https://gist.github.com/hurelhuyag/7dcfba5fccd58d657b04abe13f3be7d4

**Comment by MuntashirAkon** [comment]
Merged with ddcc97ee.

**Comment by MuntashirAkon** [comment]
I think it's better if we create a generator out of the information based on `list` and `removal` keys (we only need `id`, `list` and `removal`). Also, the JSON is malformed. They've used non-standard symbol `null` which should be replaced by either `""` or `[]`.

**Comment by gnuhead-chieb** [comment]
yeah ofcource i can make parser to integrate to new list.
but i'm integrating manually and adding descriptions for send pull request to UAD repo

**Comment by MuntashirAkon** [comment]
> yeah ofcource i can make parser to integrate to new list.

No, I mean to do it in the App Manager's side where a user can configure them from, say, a dialog. You just replace the nulls with the valid JSON symbols, and I can parse the rests in my end.

**Comment by gnuhead-chieb** [comment]
> You just replace the nulls with the valid JSON symbols, and I can parse the rests in my end.

ok so ask it to auther of UAD instead of me.this problem appears on upstream repo too

**Comment by MuntashirAkon** [comment]
> ok so ask it to auther of UAD instead of me.this problem appears on upstream repo too

I see.

**Comment by MuntashirAkon** [comment]
> Did you managed to get your changes merged with the upstream?

@gnuhead-chieb: Any update on this?

**Comment by gnuhead-chieb** [comment]
> > Did you managed to get your changes merged with the upstream?
> 
> @gnuhead-chieb: Any update on this?

Not yet.As I wrote before,I was adding manually for add descriptions.
But I will giving up adding manually and make script for the migration because there are too many cases and no end in sight.

**Comment by gnuhead-chieb** [comment]
I will work on this

**Comment by MuntashirAkon** [comment]
> I will work on this

What will you work on exactly? Add the items from your list that wasn't merged with UAD?

**Pull request closed without merging**
