### PR TITLE
Fix documentation for the installer constant INSTALL_BYPASS_LOW_TARGET_SDK_BLOCK

### PR DESCRIPTION
**Pull request by drogga**
Fix documentation for the installer constant INSTALL_BYPASS_LOW_TARGET_SDK_BLOCK

### CODE REVIEW

**Comment by drogga** [comment]
@MuntashirAkon
...

**Comment by drogga** [comment]
@MuntashirAkon 
I probably should've commented on the commit instead, so you could've fixed it by yourself...

**Comment by MuntashirAkon** [comment]
It appears typo is in the [upstream](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/content/pm/PackageManager.java;l=1662;drc=d5554ffe41c432d549dda40fc23a892114f8b2c0). Therefore, altering it here is maybe useless as it may be retained again during the next iteration. If you're willing to sign a CLA from Google, consider fixing in the upstream, or open an issue in their issue tracker.

If you want to merge it here anyway, you need to alter your commit message to make it more informative. We follow Linux's standard for git as specified in the contributing guidelines which requires an informative commit message. An example is:
```
Fix documentation for the installer constant INSTALL_BYPASS_LOW_TARGET_SDK_BLOCK

Signed-off-by: drogga <53332345+drogga@users.noreply.github.com>
```

**Comment by drogga** [comment]
Done I think, but if that's not it, then you should be able to edit it, because `Allow edits by maintainers` is enabled, so it shouldn't be a problem, because if I have to force push it somehow, then I don't know how and I use GH in a browser only, no app, compiler or anything such with more options.
Yes. I would like it fixe / merged, here, even tho the typo is upstream (I didn't know).

**Comment by drogga** [comment]
@MuntashirAkon Please check...

**Pull request merged**
