### PR TITLE
possible readme in spanish?

### PR DESCRIPTION
**Pull request by gallegonovato**
Good afternoon:

I do not know if it is well done what you were telling me.

What I do not understand is why the images are not seen ....

A hug and I apologize if I did something wrong.

### CODE REVIEW

**Comment by gnuhead-chieb** [comment]
1.
Readme written in Markdown,not plain text.
You have to rename extension to .md

2.
Directory you put translated readme is for documentation.You should make dedicated directory for that(like readme folder)

3.
You should add link of translated Readme to original one

See example here: https://github.com/VueTubeApp/VueTube

**Review by gnuhead-chieb — CHANGES_REQUESTED** [review]
Also,Don't translate filename in fastlane.

**Comment by MuntashirAkon** [comment]
Please do not make frequent changes after opening a PR. Make your changes and then open a PR. A lot of people watches all the activities of the repository. They might feel disturbed by your constant commits which are delivered by E-Mails unless they exclusively unsubscribe which they may not be in a position to right now.

**Comment by gallegonovato** [comment]
Good afternoon @MuntashirAkon :

I better close it because I don't know what I did that messed everything up.

I'm getting confused a lot here, I still don't know much about github. I don't know if it can be deleted. If you want I can send you the files by email in case they are useful?

Please excuse me for such a huge mistake

Best regards

**Comment by gnuhead-chieb** [comment]
@gallegonovato 
If you cannot use git command,I recommend Gittyup.It easy to use.
https://github.com/Murmele/Gittyup

**Comment by gnuhead-chieb** [comment]
@gallegonovato
I commited for you,Merge this PR
https://github.com/gallegonovato/AppManager/pull/1

**Comment by gallegonovato** [comment]
Good afternoon @gnuhead-chieb

THANK YOU VERY MUCH FOR ALL YOUR WORK. I STILL HAVE A LOT TO LEARN ABOUT GITHUB. I ALSO FIND THAT IN SOME THINGS I HAVE RESPECT OR FEAR :(

I REALLY DON'T KNOW HOW TO THANK YOU.

So now I can make some changes in the text I saw, no problem. No harm to anyone?

A hug and thank you very much

**Comment by gnuhead-chieb** [comment]
@gallegonovato 
Stop conflicting repo,Revert these changes and forcepush my pr on your repo

**Comment by gnuhead-chieb** [comment]
1. Run `git rebase -i HEAD~5`
2. replace pick to drop
3. Merge PR and squash
4. Force push commits

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you for your time and help.

But I didn't do anything. I just put things on https://github.com/gallegonovato/AppManager/pull/1/files

From the beginning I made a few changes from the initial description. Since some things were repeated and others were redundant when translated to Spanish. 

I make the changes in the link that I told you. Since as they explained to me this way it would not harm anyone.

I am sorry if I did something wrong. The only thing if this causes problems I send you if you want by email the things and thus would not give headaches.

Best regards

**Review by gnuhead-chieb — APPROVED** [review]

**Comment by gallegonovato** [comment]
Good afternoon @gnuhead-chieb

I just checked and I think there is a bug in the Readme in English and Spanish. Since it says:

irectly at muntashirakon [at] riseup [dot] net (FINGERPRINT

There would be something missing in that [at] or [dot] . Since it is seen in the final result.

Best regards

**Comment by gnuhead-chieb** [comment]
> There would be something missing in that [at] or [dot] . Since it is seen in the final result.

Sorry,I'm not sure I understand what you are trying to say, I'm guessing you mean [at] and [dot] should appear as "@" and "."?
If so, these are not markdown or html command.
It is just purposely replaced in this way to avoid bots that automatically collect email addresses.

**Comment by gallegonovato** [comment]
Good afternoon @gnuhead-chieb

 In the readme it appears: App Manager accepts any offer of funding/grants. Representatives of the interested organization can contact the owner directly at muntashirakon [at] riseup [dot] net (FINGERPRINT: 7bad37c2981e41f8f6abea7f58f0b4f26c346fce). 

But I don't know if I can modify it since it is https://github.com/MuntashirAkon/AppManager#donation-and-funding (in MuntashirAkon's readme) 

A hug and thanks for your time

**Comment by gallegonovato** [comment]
Good afternoon @MuntashirAkon.

I think in your readme there is a flaw. I'm referring to this file: https://github.com/MuntashirAkon/AppManager#readme and more specifically in https://github.com/MuntashirAkon/AppManager#donation-and-funding

In the part where it says:

Representatives of the interested organization can contact the owner directly at muntashirakon [at] riseup [dot] net (FINGERPRINT: 7bad37c2981e41f8f6abea7f58f0b4f26c346fce).

I think that the [at] and [dot] are wrong. I don't know if it would be:

Representatives of the interested organization can contact the owner directly at Muntashirakon at Riseup.net (FINGERPRINT: 7bad37c2981e41f8f6abea7f58f0b4f26c346fce).

I don't know what you think.

Receive a warm embrace

**Comment by MuntashirAkon** [comment]
> I think in your readme there is a flaw. I'm referring to this file: https://github.com/MuntashirAkon/AppManager#readme and more specifically in https://github.com/MuntashirAkon/AppManager#donation-and-funding

It's perfectly fine as it is. Thank you.

**Comment by MuntashirAkon** [comment]
@gallegonovato: According to a review by a Spanish friend of mine, some of your machine translations in the docs section are completely gibberish and mean completely different things. Machine translations can be used as helpers, but using them directly is not allowed as they create more problems than solving anything, and **you shall be blocked from contributing to this project if you do this ever again.**

**Comment by gallegonovato** [comment]
Good afternoon: 

As you wish. If a Spaniard does not speak Spanish.

If the terms as you comment I know what they are. And I translate it I think it is not bad to help other people. And all those words I did not know that they could not be translated, and I translated them to help. 

Since, for example, you can translate pages$settings-page$screen-lock. And I apologize if I put it in Spanish.

 But don't worry, I won't collaborate or say anything again. You are the boss. It is the same as the readme in Spanish. There are differences between English and Spanish, so you can also lock it. 

Regards

**Comment by MuntashirAkon** [comment]
If machine translations had helped, I would've translated the strings myself. There's no point in taking help from anybody else in that regard. App Manager, for instance, involve a lot of terminologies explicitly used in Android OS or in computer science in general, which they cannot translate properly. This is also why not everybody has the capabilities to translate App Manager. However, things are even worse with the docs in your case. Just look at this commit (7c562b51fd9f25b79790bdc0b96f82b0fd4cb724) where I have attempted to fix all your mistakes which gave me a headache at the end. How would you judge these mistakes? Or would you want me to spend days in fixing all your machine generated mistakes? And now you're sarcastically describing me as _the boss_. Many people made mistakes in translations in the past, but usually they weren't informed because their actions suggest that they made them quite accidentally. You're also claiming that they looked good to you. Did they at all? Since you're alleging me to be _the boss_, let me demonstrate an example of your _good translations_ despite already mentioning them in the previous post:

**Original Text**
```tex
App Manager is distributed using the following sources. Unofficial sources may distribute modified versions of App
Manager, and none but you shall be responsible for the consequences of using such distributions.
\begin{enumerate}
    \item Official F-Droid repository.\footnote{For distributing normal releases only}\\
    \textit{Link:} \url{https://f-droid.org/packages/io.github.muntashirakon.AppManager}
    \item GitHub repository.\\
    \textit{Normal releases:} \url{https://github.com/MuntashirAkon/AppManager/releases}\\
    \textit{Debug releases:} \url{https://github.com/MuntashirAkon/AppManager/actions}
    \item Telegram.\\
    \textit{Normal releases:} \url{https://t.me/AppManagerChannel}\\
    \textit{Debug releases:} \url{https://t.me/AppManagerDebug}
\end{enumerate}
```

**Your translation**
```tex
App Manager se distribuye utilizando las siguientes fuentes. Las fuentes no oficiales pueden distribuir versiones modificadas de App
Manager, y nadie más que usted será responsable de las consecuencias de utilizar dichas distribuciones.
\begin{enumerate}
 \item Repositorio oficial de F-Droid.\item Nota a pie de página{para distribuir versiones normales}\item
 \textit{enlace:} \url{https://f-droid.org/packages/io.github.muntashirakon.AppManager}
 \item Repositorio GitHub.\item
 \textit{Los lanzamientos normales:} \URL: https://github.com/MuntashirAkon/AppManager/releases
 \Título del texto: \"Liberaciones de depuración\". \url{https://github.com/MuntashirAkon/AppManager/actions}
 |Telegrama.\\N-
 \Texto de la publicación normal |https://t.me/AppManagerChannel
 \Texto de las versiones de depuración |https://t.me/AppManagerDebug
\end{enumerate}
```

The translation looks as if you've paid no attention at all, even to somebody who does not have any idea how Spanish looks like. It looks as if you've just copied and pasted the original text in the translator and after it generated a translation, you just copied back.

Yes, I do feel that you're genuinely trying to help people. But it's actually increasing more burden as you can see in the commit. I can only give a few hours per week into this project, and if I were to spend it all fixing your issues, there would be no progress in the development of features at all.

**Comment by MuntashirAkon** [comment]
Closing on request from the author.

**Pull request closed without merging**
