### PR TITLE
CoC deleted

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
Why should the CoC be deleted?

**Comment by comradekingu** [comment]
@MuntashirAkon Same reason it shouldn't be instated.
It is an ugly document that nobody actually pledged their allegiance to, doesn't do anything useful, very few people read, and you get false security and anti-meritocracy as a result.

#146 is a much better idea

**Comment by MuntashirAkon** [comment]
> It is an ugly document that nobody actually pledged their allegiance to, doesn't do anything useful, very few people read, and you get false security and anti-meritocracy as a result.

Yes, but this doesn't mean that it shouldn't exist. Like few people actually read the docs and I have to link the docs all the time in the TG group but it doesn't mean that the docs shouldn't exist. Same goes for the _disclaimer_ dialog that you see when you open AM for the first time.

That being said, AM community does have some rules and regulations (you would've known it very well if you were in the TG group) that is enforced without exceptions. CoC comes in handy when such situation occurs (the reason I've added it is because such situation has already occurred once, and I had no choice but to apologise because I didn't have any CoC at that time). I hope you've understood the situation now.

**Comment by comradekingu** [comment]
@MuntashirAkon The docs do something, and serve a specific purpose. The problem here is not reading this additional material is an additional problem.

There is nothing you can't enforce with this CoC that you can't enforce anyhow. In actual fact "harassment" is redundant to law. There however is a lot of authoritarian stuff in there. The idea that problems occur just the same is precisely why having this CoC doesn't actually help in any manner. It is counterproductive insofar as someone is fooled to the contrary. The premise of disobeying a textfile isn't going to stop an antisocial person carrying out antisocial behavior.
I would never have contributed if there was a CoC.

**Comment by MuntashirAkon** [comment]
> There is nothing you can't enforce with this CoC that you can't enforce anyhow.

Having a document serves its purpose. If I have no document, I can't present any evidence when such arguments take place. I, in general, don't like people to get hurt by my behaviour even if he's a complete lunatic. Having a community guideline prevents it as I don't have to say anything other than linking a documentation.

> There however is a lot of authoritarian stuff in there.

I agree. But a community isn't exactly a place to practise democracy either. Probably, a modified CoC might work.

**Comment by comradekingu** [comment]
@MuntashirAkon There is nothing to argue, you are the maintainer. Indisputable.
Linking to that completely vague document does _nothing_. If doing something wrong was the problem, being _linked to a document_ isn't going to do a whole lot. Much less this document. You have to actually read into it some intent, and chances of reading it back out is a case of guessing what maintainers meant by putting it in.

It not being a democracy doesn't mean it should be worse than "benevolent dictator".

> "Other conduct which could reasonably be considered inappropriate in a
>  professional setting"

is awful.

Being responsible for removing commits because someone is found to be offensive is laughable.

and then this anti-human gem

>The use of sexualized language or imagery and unwelcome sexual attention or advances

The navigation of social hierarchy and interaction in written form is as futile as making a document hinging on the interpretation of other parties. Intent matters.

**Comment by MuntashirAkon** [comment]
So, what would you do if such occurrence took place? Blocking/removing a user from the community for violating unwritten rule(s) is even more dictatorial and keeping him is a burden.

**Comment by comradekingu** [comment]
@MuntashirAkon I mean if the intent is just to cause harm, and there is no benefit.
However just removing someone doesn't teach them anything. If I was doing something wrong, I'd like to know how to do something about it. Otherwise chances are the behavior is just going to move somewhere else.
Blocking isn't more dictatorial, it is just not passive aggressive.

You get a warning, and a chance to do better and prove yourself. Then possibly some time off to think about things, and then out the door. Or whatever works.

**Comment by MuntashirAkon** [comment]
FYI: https://codeberg.org/Codeberg/org/pulls/18/files

**Comment by comradekingu** [comment]
@MuntashirAkon It is indicative of the shift towards outright political propaganda of recent years.
It isn't as if intellectual rigor somehow stems out of the doctrine of a text-file.
What will happen is the last good moderators who have laid claim to specific articles will be driven out, and it will
be increasingly easy to do so. I saw a service to divert tracking away from Wikipedia, which I guess means they do analytics too now.

**Comment by MuntashirAkon** [comment]
> they do analytics too now.

Yes, Wikipedia even uses pixel tracking.

**Pull request merged**
