### PR TITLE
Display duplicated uses permission in app details when load it first time.

### PR DESCRIPTION
**Pull request by d4rkk3y**
Screenshot_2021-07-31-22-05-53-439_io github muntashirakon AppManager debug
This loop https://github.com/MuntashirAkon/AppManager/blob/2ccf6dce6e0638bfd9167abfb7b647ea69bc0d20/app/src/main/java/io/github/muntashirakon/AppManager/details/AppDetailsActivity.java#L93-L95 was call again here https://github.com/MuntashirAkon/AppManager/blob/2ccf6dce6e0638bfd9167abfb7b647ea69bc0d20/app/src/main/java/io/github/muntashirakon/AppManager/details/AppDetailsActivity.java#L111-L114 in method loadTabs.
Maybe it make AM display duplicated "uses permission" because method https://github.com/MuntashirAkon/AppManager/blob/2ccf6dce6e0638bfd9167abfb7b647ea69bc0d20/app/src/main/java/io/github/muntashirakon/AppManager/details/AppDetailsViewModel.java#L1219-L1224 is not thread safe? 
Make that method synchronized also work.

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
As you've implied, this problem is indeed created by the `CopyOnWriteArrayList` which I will attempt to fix now. The other one (**for loop**) is actually the result of a more underlying problem which I'll also try to fix. Thanks for reporting these issues.

---

Next time you attempt to contribute, please delete the branch that's already been merged from your side or rebase with the master branch of this repository. Your current repository, for instance, contains residues from your old branch which makes it impossible for me to merge. (We also don't allow merging from GitHub, we do it manually using the [`.patch`](https://github.com/MuntashirAkon/AppManager/pull/537.patch) file.)

**Comment by d4rkk3y** [comment]
Actually, this merge request can not solve root of the problem. I should have created a Issue instead. Can I close this PR and create a issue?

**Comment by MuntashirAkon** [comment]
> Can I close this PR and create a issue?

No need. I will close this PR when I'm done with these issues.

**Comment by MuntashirAkon** [comment]
Should be fixed in a4c4ec30

**Pull request closed without merging**
