### PR TITLE
Update Issue template

### PR DESCRIPTION
**Pull request by gnuhead-chieb**
Contents of this PR:
* Prohibit creating issue that does not follow the issue template
* Trackers and library addition requests will directed to the android-libraries repository
* Encourage users to read Docs before creating an issue
* Create issue template for documentation improvement

### CODE REVIEW

**Comment by gnuhead-chieb** [comment]
Preview here
https://github.com/gnuhead-chieb/AppManager/issues/new/choose

**Comment by gnuhead-chieb** [comment]
Might as well close the discussion page.There is already an issues page, and the order on the discussion page is not good.

**Review by MuntashirAkon — APPROVED** [review]
Great work! Thanks.

**Comment by MuntashirAkon** [comment]
> Might as well close the discussion page. There is already an issues page, and the order on the discussion page is not good.

Yes, you're correct. The **Help Wanted** template is enough for this. But I shall wait until @amcommunity is up and running which should be very soon.

**Pull request merged**
